import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

interface FAQProps {
  question: string;
  answer: string;
  value: string;
}

const FAQList: FAQProps[] = [
  {
    question: "How accurate are the summaries generated by the tool?",
    answer: "Our AI is trained to provide highly accurate and concise summaries, extracting key information while preserving the context of the original document.",
    value: "item-1",
  },
  {
    question: "Which document formats are supported?",
    answer:
      "We support a wide range of formats including PDF, Word, TXT, and more for easy uploading and summarization.",
    value: "item-2",
  },
  {
    question:
      "Is my data secure when using this tool?",
    answer:
      "Yes, all documents are processed with end-to-end encryption, ensuring your data is kept safe and private.",
    value: "item-3",
  },
  {
    question: "Can I provide feedback on the summaries generated?",
    answer: "Yes, we value user feedback to continuously improve the accuracy and relevance of the summaries.",
    value: "item-4",
  },
  {
    question:
      "Does the tool work for domain-specific documents like legal contracts or medical papers?",
    answer:
      "Absolutely! Our AI adapts to different document types, providing domain-specific insights for industries like healthcare, finance, and more.",
    value: "item-5",
  },
];

export const FAQ = () => {
  return (
    <section
      id="faq"
      className="container py-24 sm:py-12"
    >
      <h2 className="text-3xl md:text-4xl font-bold mb-4">
        Frequently Asked{" "}
        <span className="bg-gradient-to-b from-primary/60 to-primary text-transparent bg-clip-text">
          Questions
        </span>
      </h2>

      <Accordion
        type="single"
        collapsible
        className="w-full AccordionRoot"
      >
        {FAQList.map(({ question, answer, value }: FAQProps) => (
          <AccordionItem
            key={value}
            value={value}
          >
            <AccordionTrigger className="text-left">
              {question}
            </AccordionTrigger>

            <AccordionContent>{answer}</AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>

      <h3 className="font-medium mt-4">
        Still have questions?{" "}
        <a
          rel="noreferrer noopener"
          href="#"
          className="text-primary transition-all border-primary hover:border-b-2"
        >
          Contact us
        </a>
      </h3>
    </section>
  );
};
